## Python Review

In [1]:
# print 'hello'
print('hello')

hello


In [2]:
# declare a variable: integer, float, bool, string
my_integer = 5
my_float = 5.2
print(type(my_integer), type(my_float))

my_bool = True
my_other_bool = False

my_string = 'hello my name is matt'

# integer vs float ???
# float 1.22222222222, 1.32092043, -122.0, 1.0, 9.0, intgers 1, 2, 3, 10000, -5, -11000

<class 'int'> <class 'float'>


In [6]:
# make an 'if then' statement: if my_bool is True than print 'my bool is true'
my_bool = True
if my_bool == True:
  print('true')

val = 0.7
if val > 0.5:
  print('> 0.5')
elif val <= 0.5:
  print('<= 0.5')

# ==, <, >, <=, >=, !=

true
> 0.5


In [10]:
# make a list: my_list, append an item to the list
my_list = [1, 2, 3, 4, 5]
print(len(my_list))

my_list.append(5)
print(my_list)

my_list = my_list + [10, 6]
print(my_list)

5
[1, 2, 3, 4, 5, 5]
[1, 2, 3, 4, 5, 5, 10, 6]


In [15]:
# create a 'for loop': for i in range append an item to our list
my_list = ['1a', '2a', '3a']
for i in my_list:
  print(i)

1a
2a
3a


In [18]:
# index a list, splice a list
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

print(my_list[2])

print(my_list[2:5])

3
[3, 4, 5]


In [21]:
# make a definition: given a value x, return x * 2 + 10

def give_me_a_number(num):
  if num > 1:
    val = 100
  elif num <= 1:
    val = 0
  return val

val = give_me_a_number(2)
print(val)

100


## Basics of PyTorch

In [22]:
# import pytorch library
import torch

In [60]:
# make an array(vector): (from list), torch.rand, torch.randn, 
#                        torch.arange, torch.ones, torch.zeros
array_from_list = torch.FloatTensor([1.0, 1.5, 2.0, 2.6, 3.8])
print(array_from_list)
array = torch.rand(10)
print(array)
array_1 = torch.ones(10, 10)
print(array_1)

tensor([1.0000, 1.5000, 2.0000, 2.6000, 3.8000])
tensor([0.0748, 0.0151, 0.0662, 0.1557, 0.8632, 0.2478, 0.0996, 0.6463, 0.4178,
        0.7835])
tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])


In [61]:
# make a matrix:
tensor = torch.randn(100, 10, 10)
print(tensor.shape)

torch.Size([100, 10, 10])


In [62]:
print('cuda is available:', torch.cuda.is_available(), 
      ', device name:', torch.cuda.get_device_name())

# move a tensor to the GPU
tensor = torch.randn(10, 10, 10)
print(tensor.shape, tensor.device)

tensor = tensor.cuda()
print(tensor.shape, tensor.device)

cuda is available: True , device name: Tesla T4
torch.Size([10, 10, 10]) cpu
torch.Size([10, 10, 10]) cuda:0


In [63]:
# move a tensor back to the CPU
tensor = torch.randn(10, 10, 10).cuda()
print(tensor.shape, tensor.device)
tensor = tensor.cpu()
print(tensor.shape, tensor.device)

torch.Size([10, 10, 10]) cuda:0
torch.Size([10, 10, 10]) cpu


## Basic Operations of Linear Algebra in PyTorch

In [65]:
# perform scalar addition with a vector and a matrix
matrix = torch.zeros(8, 8)
print(matrix)
print(matrix + 2)

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])
tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.]])


In [66]:
# perform scalar mutliplication with a vector and a matrix
matrix = torch.ones(8, 8)
print(matrix)
print(matrix * 5)

tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.]])


In [67]:
# create vectors u and v, print shapes
u = torch.rand(10)
v = torch.ones(10)
# perform vector addition between vectors u and v
print(u)
print(v)
print(u + v)

tensor([0.1420, 0.6750, 0.6774, 0.7386, 0.0827, 0.5492, 0.7006, 0.0089, 0.4120,
        0.9836])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([1.1420, 1.6750, 1.6774, 1.7386, 1.0827, 1.5492, 1.7006, 1.0089, 1.4120,
        1.9836])


In [68]:
# perform matrix-matrix multiplication between a matrix A and a matrix B

A = torch.rand(3, 2)
B = torch.rand(2, 1)
print(A.shape, B.shape)

result = torch.mm(A, B)
print(result.shape)

# result_b = A * B -> gives error because shapes (3, 2) and (2, 1) do not match.

# Matrix Multiplication
# A (axb), B(cxd)
# b = c

# element-wise matrix multiplication
# A (axb), B(cxd)
# a = c and b = d

# broadcasting
#A (axb), B(cx1)
# c = a


torch.Size([3, 2]) torch.Size([2, 1])
torch.Size([3, 1])


In [69]:
# create a matrix A and a matrix B, print shapes

A = torch.rand(3, 2)
B = torch.rand(3, 2)
print(A.shape, B.shape)

result = A * B
print(result.shape)

torch.Size([3, 2]) torch.Size([3, 2])
torch.Size([3, 2])


In [57]:
# create a matrix A and a vector v, print shapes
A_T = torch.randn(3, 9)
print(A_T.shape)

A_T = A.transpose(1, 0)
print(A_T.shape)
# perform the transpose of matrix A and vector v

# print shape of results
matrix = torch.randn(100, 3, 16, 16)
print(matrix.shape)

# permute
matrix_p = matrix.permute(3, 2, 1, 0)
print(matrix_p.shape)

torch.Size([3, 9])
torch.Size([9, 3])
torch.Size([100, 3, 16, 16])
torch.Size([16, 16, 3, 100])


In [70]:
# perform addition with broadcasting between A and v
A = torch.rand(3, 2)
B = torch.rand(3, 1)
print(A.shape, B.shape)

result = A + B
print(result.shape)

torch.Size([3, 2]) torch.Size([3, 1])
torch.Size([3, 2])


In [71]:
# perform multiplication with broadcasting between A and v
A = torch.rand(3, 2)
B = torch.rand(3, 1)
print(A.shape, B.shape)

result = A + B
print(result.shape)

torch.Size([3, 2]) torch.Size([3, 1])
torch.Size([3, 2])


In [74]:
# create a vector v and a vector u, print shapes
v = torch.FloatTensor([1, 2, 3, 4, 5, 6])
u = torch.FloatTensor([0.1, 0.2, 0.3, 0.4, 0.5, 0.6])
# perform outer product on vector v and vector u
outer = torch.outer(v, u)
print(outer, outer.shape)

tensor([[0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000],
        [0.2000, 0.4000, 0.6000, 0.8000, 1.0000, 1.2000],
        [0.3000, 0.6000, 0.9000, 1.2000, 1.5000, 1.8000],
        [0.4000, 0.8000, 1.2000, 1.6000, 2.0000, 2.4000],
        [0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000],
        [0.6000, 1.2000, 1.8000, 2.4000, 3.0000, 3.6000]]) torch.Size([6, 6])
